### ISSUE TITLE
High: Leaving a 1:1 conversation after sending a message fails

### ISSUE THREAD

**Issue by hagitmer** [Hacknocraft/AppFriendsUI#24]
The problem with the 1-1 conversations seems to be that if the user who leaves the message sends the last message, the dialog comes back to the list and is titled as "Private Conversation"; it seems that the last message the leaving user sent is appearing as an unread message, so the api call is pulling the conversation back down to the user who left's device.

Note that this also happens in Android (https://github.com/Hacknocraft/AppFriendsAndroidCore/issues/38)

**Comment by laeroah** [comment]
@hagitmer ok, thanks for reporting it. will correct this issue in the up coming release. I think this problem is a side effect after we started to support sync messages across multiple devices. We use to not push down messages again if they are already pushed down, and since we now need to push messages down again, we need to handle this case.

**Comment by laeroah** [comment]
@hagitmer actually, I think got confused it. We should already fixed this problem a few releases back. Please let me know if this is still an issue after updating the SDK.
